### ISSUE TITLE
Feature Request: Add an option to configure a bookmark to always open in a specific tab container

### ISSUE THREAD

**Issue by pridey** [Rob--W/bookmark-container-tab#13]
Hi @Rob--W 

Thanks so much for going to the effort of creating this addon, it's almost exactly what I've been looking for.  What would make it perfect is if you could add an additional feature allowing you to configure a bookmark to always open in a specific tab container.

More than happy to help you test it if you can be bothered with some scope creep ;-)

Cheers,
Tom

**Comment by Rob--W** [comment]
Hi @pridey, this feature has been requested before in #2, but requires changes in Firefox to implement it.

Since there is already an issue for this, I'm closing this one. Thanks for taking your time to write this feature request though!
