### ISSUE TITLE
Request: Add to Bookmarks Sidebar Context Menu

### ISSUE THREAD

**Issue by MichaelTunnell** [Rob--W/bookmark-container-tab#3]
First of all, thank you very much for making this! This will save a lot of time for people.

I did notice something that is missing. This works great from the Alt+B menu and from the Bookmarks Toolbar but it doesn't seem to work in the Bookmarks Sidebar. I use the Sidebar 99% of the time because takes up less space with my excessive amount of bookmarks. :) 

If you could add the context menu option to bookmarks in the Sidebar then that would be fantastic for my usage!

Thanks again for making this extension!

**Comment by Rob--W** [comment]
This is not possible yet, but will be possible in a future version of Firefox (64?). Patches are currently under review: https://bugzilla.mozilla.org/show_bug.cgi?id=1419195

**Comment by MichaelTunnell** [comment]
That's great! I am glad to have this whenever, I'm fairly patient. :)

**Comment by Rob--W** [comment]
The feature finally landed in Firefpox 66, which will ship to release next week (you can try Firefox Developer Edition, Firefox Beta or Firefox Nightly if you want to see what it's like now).


![](https://mdn.mozillademos.org/files/16554/extension_context_menu.png)
