### ISSUE TITLE
Name of menu choice not coherent with the existing one (English)

### ISSUE THREAD

**Issue by rloutrel** [Rob--W/bookmark-container-tab#5]
The menu Entry is "Open in New Container Tab" when the other entries are:

- Open in **a** New Tab

- Open in **a** New Window

→ When applying the fix of issue 1 (sort the entries), it becomes obvious...

Not a huge problem, but I am seeing it every times and though it could be useful to report it.

**Comment by Rob--W** [comment]
The current label is based on the context menu of regular links, which shows "Open link in New Tab" (without "a").

I wouldn't mind adding an "a". Do you want to submit a PR (and call the commit title something like `Add "a" in menu label for consistency with built-in menu items`)?
