### ISSUE TITLE
Feature request- open bookmarks unloaded

### ISSUE THREAD

**Issue by piecevcake** [Rob--W/bookmark-container-tab#9]
Hi, thanks for this very useful addon.

Often I need to load a large folder of bookmarks, which have been retitled using Tab Retitle (or in bookmarks properties), then apply Tree tabs structure -workaround to get tabs into correct containers!

Unfortunately loading large numbers of tabs jams up my PC and loses the custom titles (which Tab Retitle can catch if they are opened manually one at a time.)

So could you possibly add an option to open the bookmarks unloaded?  Tree tabs does this and it is just great.

**Comment by Rob--W** [comment]
What is "large number of tabs"?

This can be implemented by passing `discarded: true` at https://github.com/Rob--W/bookmark-container-tab/blob/1fe029d5b0fa90b42b237bd7926688c48268ce57/background.js#L31 , but I'm wondering whether this should be the default, or an optional new option in a (new) options page.

**Comment by piecevcake** [comment]
Thanks for the speedy reply! yesterday 165 tabs - on my poor laptop

**Comment by piecevcake** [comment]
I would suggest default.  As there is already an easy option to reload all tabs or selected tabs. ))
It is the default in Tree Tabs and works great.

**Comment by Rob--W** [comment]
165... is a lot!

I do indeed think that it makes sense to open some tabs in discarded mode past a certain threshold. Do you know the default behavior when you try to open that many bookmarks? Will Firefox try to open all at once, or are some discarded at some point.

**Comment by piecevcake** [comment]
FF opens them all.  Watch paint dry, get a headache.  FF completely ceases to function till all tabs loaded.

Edit- IDK with bookmarks, that was FF context open tabs in new container I used yesterday.

Even if it loads 1 tab, that custom tab title is lost.

(Lots of tabs - When doing research, I keep reject tabs marked as such, to avoid repeating them)

**Comment by piecevcake** [comment]
Hi Rob any progress with this? It's really not useable to retrieve folders of tabs without it.

See Tree tabs addon which loads all tabs discarded.

**Comment by Rob--W** [comment]
This fell off my radar. Do remind me if you don't see any activity in the next two weeks.

**Comment by piecevcake** [comment]
Thanks Rob! :)
    
    
        -------- Original Message --------
          DATE: 9/06/2020, 12:20:24 AM
          FROM: Rob Wu <notifications@github.com>
          TO: Rob--W/bookmark-container-tab
          <bookmark-container-tab@noreply.github.com>
          CC: piecevcake <github.com@vplaw.co.nz>, Author
          <author@noreply.github.com>
          SUBJECT:..Re: [Rob--W/bookmark-container-tab] Feature
          request- open bookmarks unloaded (#9)
        
        
        
      
      
      This fell off my radar. Do remind me if you don't see any
        activity in the next two weeks.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rob--W/bookmark-container-tab/issues/9#issuecomment-640568447",
"url": "https://github.com/Rob--W/bookmark-container-tab/issues/9#issuecomment-640568447",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Rob--W** [comment]
Published as version 1.3, it's now available at https://addons.mozilla.org/en-US/firefox/addon/open-bookmark-in-container-tab/

**Comment by piecevcake** [comment]
Thanks Rob that is an improvement... now only 10 tab titles are lost... :-/

**Comment by Rob--W** [comment]
> Unfortunately loading large numbers of tabs jams up my PC and loses the custom titles (which Tab Retitle can catch if they are opened manually one at a time.)

> now only 10 tab titles are lost... :-/

I'm not familiar with Tab Retitle, but could this be a bug in that add-on? What happens if you use the built-in "Open in a New Tab" menu option on a bookmark? If you can provide a step-by-step description to reproduce your issue, I can take a look to see if there is a bug in my add-on (or the other add-on, or maybe even in Firefox).

**Comment by piecevcake** [comment]
Hi Rob, thanks for your interest.
    I'll have to check again but I think what happens is the bookmarked
    tabs are loaded with the bookmark names which are overwritten when
    the tabs are loaded, but maybe that's incorrect.
    Tab Retitle actually renames the tabs, and the custom tab names are
    saved as the bookmark names when the tabs are bookmarked.
    Tab Retitle also can restore the bookmark name to the tab after it
    is reloaded.
    
    My point really was, that it would be best to have none of the
    bookmarks loaded, it still uses resources and it is super simple to
    click on the tab to load it.
    
    
        -------- Original Message --------
          DATE: 2/08/2020, 9:18:54 AM
          FROM: Rob Wu <notifications@github.com>
          TO: Rob--W/bookmark-container-tab
          <bookmark-container-tab@noreply.github.com>
          CC: piecevcake <github.com@vplaw.co.nz>, Author
          <author@noreply.github.com>
          SUBJECT:..Re: [Rob--W/bookmark-container-tab] Feature
          request- open bookmarks unloaded (#9)
        
        
        
      
      
      
        Unfortunately loading large numbers of tabs jams up my PC and
          loses the custom titles (which Tab Retitle can catch if they
          are opened manually one at a time.)
      
      
        now only 10 tab titles are lost... :-/
      
      I'm not familiar with Tab Retitle, but could this be a bug in
        that add-on? What happens if you use the built-in "Open in a New
        Tab" menu option on a bookmark? If you can provide a
        step-by-step description to reproduce your issue, I can take a
        look to see if there is a bug in my add-on (or the other add-on,
        or maybe even in Firefox).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rob--W/bookmark-container-tab/issues/9#issuecomment-667588379",
"url": "https://github.com/Rob--W/bookmark-container-tab/issues/9#issuecomment-667588379",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
